spring:
  application:
    name: sharding-demo
  shardingsphere:
    schema:
      name: lic_db
    rules:
      sharding:
        tables:
#          test:
#            actual-data-nodes: lic-c-$->{0..1}.test_$->{2021..2022}_$->{1..12}
#            table-strategy:
#              # 分表
#              standard:
#                sharding-column: create_time
#                shardingAlgorithmName: bytablesignandid
#            # 分库
#            databaseStrategy:
#              INLINE:
#                sharding-columns: id
#                algorithm-expression: lic-c-$->{id.intdiv(2)%2}\
          star_demo:
            actual-data-nodes: lic-c-$->{0..1}.star_demo
#                分片算法名称和配置
        sharding-algorithms:
          #          策略名称 表策略 按照月份
#          bytablesignandid:
#            type: CLASS_BASED
#            props:
#              algorithmClassName: com.sharding.demo.shardingdemo.sharding.TablesShardingAlgorithm
          #           策略名称 库策略 按照 id
          bydbid:
            type: INLINE
            props:
              algorithm-expression: lic-c-$->{id.intdiv(2)%2}
#      广播表规则列表
        broadcast-tables:
          - star_demo
    datasource:
      names: lic-c-0,lic-c-1
      lic-c-0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/lic-c-0?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
        username: root
        password: 123456
        pool-name: HikariPool-lic-c-0
        #连接建立超时时间 单位ms 默认30000
        connection-timeout: 30000
        # 连接的最大持有时间,0为无限制 默认 30 分钟
        max-lifetime: 30000
        # 连接池中最大维持的连接数量 默认初始连接池是 10
        maximum-pool-size: 50
      lic-c-1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/lic-c-1?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
        username: root
        password: 123456
        pool-name: HikariPool-lic-c-1
        #连接建立超时时间 单位ms 默认30000
        connection-timeout: 30000
        # 连接的最大持有时间,0为无限制 默认 30 分钟
        max-lifetime: 30000
        # 连接池中最大维持的连接数量 默认初始连接池是 10
        maximum-pool-size: 50
    sharding:
      default-data-source-name: lic-c-0
      default-database-strategy:
        none: 1
    props:
      sql-show: true
      sql-simple: true
server:
  port: 9011


mybatis-plus:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.sharding.demo.shardingdemo.entity



